
---
version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - ./airflow:/opt/aiflow
    env_file:
    - .env
    ports:
      - 8080:8080
    depends_on:
      - redis
      - postgres
  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
